-- DROP TABLE lauseet
DROP TABLE IF EXISTS RuokaAines CASCADE;

DROP TABLE IF EXISTS Aines CASCADE;

DROP TABLE IF EXISTS RuokaKategoria CASCADE;

DROP TABLE IF EXISTS Kategoria CASCADE;

DROP TABLE IF EXISTS Ruoka CASCADE;

DROP TABLE IF EXISTS Kayttaja CASCADE;
